name: triggerAuto

on:
   workflow_run:
      workflows: triggerOnPush
      branches: main
      types: completed
   workflow_dispatch:
    inputs:
      revisionKey:
        description: 'Commit hash(first 7 char):'
        required: false
jobs:
  greet:
    name: deploying - ${{ github.event.inputs.revisionKey || github.sha}}
    runs-on: ubuntu-latest
    env:
      SOURCE_VERSION: ${{ github.event.inputs.revisionKey }}
    steps: 
    - name: Step 2
      run: echo ${GITHUB_SHA::7}
    - name: Step 3
      run: echo $SOURCE_VERSION
