name: triggerAuto

on:
   workflow_run:
      workflows: triggerOnPush
      branches: main
      types: completed
   workflow_dispatch:
    inputs:
      revisionKey:
        description: 'Commit hash(first 7 char):'
        required: false
        default: "hakan"
jobs:
  greet:
    name: deploying - ${{ github.event.inputs.revisionKey }}
    runs-on: ubuntu-latest
    env:
      SOURCE_VERSION: ${{ github.event.inputs.revisionKey }} 
    steps: 
    - name: Step
      run: echo ${GITHUB_SHA::7}
